title: "ThreatLens"
description: "Hands-on labs, OWASP, networking, privilege escalation"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: dark
search_enabled: true
heading_anchors: false
